### ISSUE TITLE
Update README.md file

### ISSUE THREAD

**Issue by sakakuGH** [CSCI-GA-2820-SU24-001/inventory#9]
As a developer,
I need to have a README.md file for the inventory system,
so that we can have a clearer procedure about how to set up, run, and test the code.

Assumptions:

By reading this file, developers will have a more efficient way to run and test our code. 

Acceptance Criteria:

Software positioning, basic functions of the software 
Show how to run the code including installation environment, startup commands, etc. 
Brief instructions for how to benefit from this microservice
Description of the basic principles of the software
Common problems description

**Comment by Ravi-Chavda** [comment]
Added PR for above change 

https://github.com/CSCI-GA-2820-SU24-001/inventory/pull/19
